# Generated by Django 2.1.2 on 2018-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181106_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], default=2018, max_length=4, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(choices=[('UR', 'Unreserved'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTH', 'Other')], default='UR', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(choices=[('USICT', 'U.S.I.C.T.')], default='USICT', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('BtechCSE', 'B.TECH - CSE'), ('BtechIT', 'B.TECH - IT'), ('BtechECE', 'B.TECH - ECE'), ('MtechCSE', 'M.TECH - CSE'), ('MtechIT', 'M.TECH - IT'), ('MtechECE', 'M.TECH - ECE'), ('MCA', 'MCA')], default='BtechCSE', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(choices=[('DEL', 'Delhi'), ('ODEL', 'Outside Delhi')], default='DEL', max_length=20),
        ),
    ]
