# Generated by Django 2.1.2 on 2018-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181114_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], max_length=4, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(choices=[('UR', 'Unreserved'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTH', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('BtechCSE', 'B.TECH - CSE'), ('BtechIT', 'B.TECH - IT'), ('BtechECE', 'B.TECH - ECE'), ('MtechCSE', 'M.TECH - CSE'), ('MtechIT', 'M.TECH - IT'), ('MtechECE', 'M.TECH - ECE'), ('MCA', 'MCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(choices=[('DEL', 'Delhi'), ('ODEL', 'Outside Delhi')], max_length=20),
        ),
    ]
