# Generated by Django 2.1.2 on 2018-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181114_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017)], max_length=4, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('UR', 'Unreserved'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTH', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('BtechCSE', 'B.TECH - CSE'), ('BtechIT', 'B.TECH - IT'), ('BtechECE', 'B.TECH - ECE'), ('MtechCSE', 'M.TECH - CSE'), ('MtechIT', 'M.TECH - IT'), ('MtechECE', 'M.TECH - ECE'), ('MCA', 'MCA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('DEL', 'Delhi'), ('ODEL', 'Outside Delhi')], max_length=20, null=True),
        ),
    ]
