# Generated by Django 2.1.2 on 2018-11-14 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181114_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.CharField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017)], max_length=4, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_no',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
