# Generated by Django 2.1.2 on 2018-11-14 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20181114_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_no',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(10000000)]),
        ),
    ]
