# Generated by Django 2.1.2 on 2018-11-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20181114_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.CharField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], max_length=4, null=True, verbose_name='Year of Admission'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
