# Generated by Django 2.1.2 on 2018-12-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20181230_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.CharField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], max_length=4, null=True, verbose_name='Year of Admission'),
        ),
    ]
