# Generated by Django 2.1.2 on 2019-01-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20181230_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
