# Generated by Django 2.1.2 on 2019-01-02 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('college', models.CharField(choices=[('USICT', 'U.S.I.C.T.')], default='USICT', max_length=10)),
                ('course', models.CharField(blank=True, choices=[('BtechCSE', 'B.TECH - CSE'), ('BtechIT', 'B.TECH - IT'), ('BtechECE', 'B.TECH - ECE'), ('MtechCSE', 'M.TECH - CSE'), ('MtechIT', 'M.TECH - IT'), ('MtechECE', 'M.TECH - ECE'), ('MCA', 'MCA')], max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('admission_year', models.CharField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], max_length=4, null=True, verbose_name='Year of Admission')),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, choices=[('DEL', 'Delhi'), ('ODEL', 'Outside Delhi')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('UR', 'Unreserved'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTH', 'Other')], max_length=20, null=True)),
                ('mobile', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
            },
        ),
    ]
