# Generated by Django 2.1.2 on 2019-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeeducation',
            name='from_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(choices=[('Unreserved', 'Unreserved'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTH', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('B.TECH - CSE', 'B.TECH - CSE'), ('B.TECH - IT', 'B.TECH - IT'), ('B.TECH - ECE', 'B.TECH - ECE'), ('M.TECH - CSE', 'M.TECH - CSE'), ('M.TECH - IT', 'M.TECH - IT'), ('M.TECH - ECE', 'M.TECH - ECE'), ('MCA', 'MCA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=11),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Outside Delhi', 'Outside Delhi')], max_length=20),
        ),
    ]
