# Generated by Django 2.1.2 on 2019-03-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('UR', 'Unreserved'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTH', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('DEL', 'Delhi'), ('ODEL', 'Outside Delhi')], max_length=20, null=True),
        ),
    ]
