# Generated by Django 2.1.2 on 2019-04-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190408_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
