# Generated by Django 2.1.2 on 2019-01-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190128_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='tweth_marks',
            field=models.IntegerField(blank=True, null=True, verbose_name='12th marks'),
        ),
    ]
