# Generated by Django 2.1.2 on 2019-03-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190301_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_1',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_2',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_3',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_4',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_5',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_6',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_7',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='semester_8',
        ),
    ]
