# Generated by Django 2.1.2 on 2019-01-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_marksheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem1',
            new_name='semester_1',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem2',
            new_name='semester_2',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem3',
            new_name='semester_3',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem4',
            new_name='semester_4',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem5',
            new_name='semester_5',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem6',
            new_name='semester_6',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem7',
            new_name='semester_7',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sem8',
            new_name='semester_8',
        ),
    ]
