# Generated by Django 2.1.2 on 2019-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190331_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooleducation',
            name='board',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schooleducation',
            name='qualificaion',
            field=models.CharField(blank=True, choices=[('Secondary', 'X (Secondary)'), ('SeniorSecondary', 'XII (Senior Secondary)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schooleducation',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schooleducation',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], null=True),
        ),
    ]
