# Generated by Django 2.1.2 on 2019-03-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190331_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooleducation',
            old_name='qualificaion',
            new_name='qualification',
        ),
    ]
