# Generated by Django 2.1.2 on 2019-01-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190102_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksheet',
            old_name='cgpa',
            new_name='CGPA',
        ),
    ]
