# Generated by Django 2.1.2 on 2019-03-01 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190301_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='backlogs',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='credits_skipped',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
