# Generated by Django 2.1.2 on 2019-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190102_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='tweth_marks',
            field=models.IntegerField(blank=True, null=True, verbose_name='12th marks'),
        ),
    ]
