# Generated by Django 2.1.2 on 2019-03-01 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190301_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='institute_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='program_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='tweth_marks',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passing_year',
            field=models.CharField(blank=True, choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], max_length=10, null=True, verbose_name='Year of Passing Out'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='primary_mobile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternative email'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='secondary_mobile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Alternative Mobile Number'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='backlogs',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Backlogs'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_name',
            field=models.CharField(max_length=100),
        ),
    ]
