# Generated by Django 2.1.2 on 2019-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentprofile_tweth_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Male', max_length=11),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institute_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='program_code',
            field=models.IntegerField(default=0),
        ),
    ]
