# Generated by Django 2.1.2 on 2019-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190301_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='data',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='category',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Project', 'Project'), ('Training', 'Training'), ('Other', 'Other')], default='Other', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ending Date'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Starting Date'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
