# Generated by Django 2.1.2 on 2019-03-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190301_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(null=True, verbose_name='Starting Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ending Date')),
                ('marks', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Aggregate Marks/CGPA')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificaion', models.CharField(choices=[('HighSchool', 'High School'), ('SeniorSecondary', 'Senior Secondary')], max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('marks', models.CharField(blank=True, max_length=5, null=True, verbose_name='Percentage/CGPA')),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], null=True, verbose_name='Year of Admission'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='passing_year',
            field=models.IntegerField(blank=True, choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True, verbose_name='Year of Passing Out'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='category',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Project', 'Project'), ('Training', 'Training'), ('Achievement', 'Achievement'), ('Other', 'Other')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='schooleducation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile'),
        ),
        migrations.AddField(
            model_name='collegeeducation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile'),
        ),
    ]
