# Generated by Django 2.1.2 on 2019-01-28 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190128_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('fathers_education', models.CharField(blank=True, choices=[('UP TO 5TH', 'UP TO 5TH'), ('UP TO 8TH', 'UP TO 8TH'), ('UP TO 10TH', 'UP TO 10TH'), ('UP TO 12TH', 'UP TO 12TH'), ('UP TO UG', 'UP TO UG'), ('UP TO PG', 'UP TO PG'), ('ANY OTHER', 'ANY OTHER')], max_length=20, null=True)),
                ('mothers_education', models.CharField(blank=True, choices=[('UP TO 5TH', 'UP TO 5TH'), ('UP TO 8TH', 'UP TO 8TH'), ('UP TO 10TH', 'UP TO 10TH'), ('UP TO 12TH', 'UP TO 12TH'), ('UP TO UG', 'UP TO UG'), ('UP TO PG', 'UP TO PG'), ('ANY OTHER', 'ANY OTHER')], max_length=20, null=True)),
                ('family_income', models.CharField(blank=True, choices=[('< 50,000', '< 50,000'), ('50,000 - 1,00,000', '50,000 - 1,00,000'), ('1,00,000 - 2,50,000', '1,00,000 - 2,50,000'), ('2,50,000 - 4,00,000', '2,50,000 - 4,00,000'), ('4,00,000 - 6,00,000', '4,00,000 - 6,00,000'), ('6,00,000 - 10,00,000', '6,00,000 - 10,00,000'), ('10,00,000 >', '10,00,000 >')], max_length=20, null=True)),
                ('school_attended_12th', models.CharField(blank=True, choices=[('GOVT', 'GOVT'), ('GOVT AIDED', 'GOVT AIDED'), ('SELF FINANCING/ UNAIDED', 'SELF FINANCING/ UNAIDED')], max_length=20, null=True)),
                ('board', models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('State Board', 'State Board'), ('NIOS', 'NIOS'), ('Madarsa', 'Madarsa'), ('Other', 'Other')], max_length=20, null=True)),
                ('aadhar_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('fathers_employment', models.CharField(blank=True, choices=[('GOVT Service, PSU', 'GOVT Service, PSU'), ('Private service', 'Private service'), ('Self employed', 'Self employed'), ('Professional', 'Professional'), ('Casual Labour', 'Casual Labour'), ('Farming, Agri-Labour', 'Farming, Agri-Labour'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], max_length=20, null=True)),
                ('mothers_employment', models.CharField(blank=True, choices=[('GOVT Service, PSU', 'GOVT Service, PSU'), ('Private service', 'Private service'), ('Self employed', 'Self employed'), ('Professional', 'Professional'), ('Casual Labour', 'Casual Labour'), ('Farming, Agri-Labour', 'Farming, Agri-Labour'), ('House wife', 'House wife'), ('Other', 'Other')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile'),
        ),
    ]
