# Generated by Django 2.1.2 on 2019-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190306_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='secondary_email',
        ),
        migrations.AlterField(
            model_name='collegeeducation',
            name='end_date',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ending Date'),
        ),
        migrations.AlterField(
            model_name='collegeeducation',
            name='start_date',
            field=models.CharField(max_length=5, null=True, verbose_name='Starting Date'),
        ),
    ]
