# Generated by Django 2.1.2 on 2019-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20190330_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeeducation',
            name='end_date',
            field=models.IntegerField(blank=True, choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True, verbose_name='Passing year'),
        ),
        migrations.AlterField(
            model_name='collegeeducation',
            name='start_date',
            field=models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], null=True, verbose_name='Year of admission'),
        ),
    ]
